variables:
  IMAGE_NAME: nest-adminjs-template
  IMAGE_FULL_NAME: ${NEXUS}/${IMAGE_NAME}:$CI_COMMIT_SHA
  WEB_NETWORK: ndb_net
  DOCKER_PORT_PROD: 3017

include:
  - project: 'devops-tools/gitlab-ci-templates/js'
    ref: main
    file:
      - '.docker-build-js.gitlab-ci.yml'
      - '.deploy-js.gitlab-ci.yml'
      - '.tests-sonar-js.gitlab-ci.yml'
stages:
  - docker-build
  - tests
  - sonarqube-check
  - deploy
tests:
  extends: .tests
  allow_failure: true
sonarqube-check:
  extends: .sonarqube-check
  allow_failure: true

deploy:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        TEAM: team-4
        VM_HOST_LOGIN: ""
        VM_HOST_IP: "10.248.55.53"
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        TEAM: team-4
        VM_HOST_LOGIN: ""
        VM_HOST_IP: "10.248.4.68"
